# Site settings
title: Ryan Adkins | Web Developer & Photographer
email: ryanadkins@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ryan Adkins is a digital artist living in Anchorage, Alaska.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ryanadkins.com" # the base hostname & protocol for your site
github_username:  jekyll

# Build settings
markdown: rdiscount
