# Site settings
title: Ryan Adkins
email: ryanadkins@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Ryan Adkins web develper and digital artist personal portfolio site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: RyanAAdkins
github_username:  ryanadkins
timezone: America/Anchorage

# Build settings
baseurl: ""
permalink: pretty
exclude: ["gulpfile.js", "node_modules", "package.json", "bower_components", "bower.json"]
markdown: rdiscount